# Generated by Django 4.1.4 on 2022-12-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_categories_rename_pictures_meal_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('kind_of_food', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
