# Generated by Django 4.1.4 on 2022-12-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_food_remove_meal_category_delete_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='kind_of_food',
            new_name='category',
        ),
    ]
